# Project information
site_name: 'Slaven Abdović | Repozitorij'
site_description: 'Kategorizirana zbirka osobnog znanstveno-istraživačkog, intelektualnog i kreativnog rada'
site_author: 'Slaven Abdović'
site_url: http://slaven-abdovic.from.hr

# Repository
repo_name: 'slavenabd/repozy'
repo_url: 'https://github.com/slavenabd/repozy'

# Copyright
copyright: 'Copyright &copy; 2018 Slaven Abdovic'

# Documents
nav:
    - Početna: index.md
    - Noćno mokrenje: 
        - 'Repozitorij noćnog mokrenja': enureza.md
        - 'Edukativni materijal za roditelje': enureza_edu.md
        - 'Preporuka obrade za rijetke uzroke enureze': enureza_prep.md
    - Kasno-prezentirajuća valvula stražnje uretre: puv.md
    - Infekcije mokraćnih putova: uti.md
    - Kronična bubrežna bolest: ckd.md
    - Prekomjerno aktivni mokraćni mjehur: oab.md
    - Posteri, predavanja i članci: art.md
    - Životopis: zivotopis.md

# Configuration
theme:
  name: 'material'
  palette:
    primary: 'teal'
    accent: 'teal'
  logo:
    icon: 'font_download'
  language: 'sh'

# Customization
extra:
  social:
    - type: 'github'
      link: 'https://github.com/slavenabd'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/in/slaven-abdovic'

# Google Analytics
google_analytics:
  - 'UA-XXXXXXXX-X'
  - 'auto'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true